pipeline:
  gcr:
    image: plugins/gcr
    repo: festive-shield-189915/fec-sheet
    tags: latest

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/sheet
    release: sheet
    values: db.user=${DB_USER},db.pass=${DB_PASS},db.host=${DB_HOST},db.name=${DB_NAME}
    prefix: 
    namespace: sheet
    secrets: [ api_server, kubernetes_token, db_user, db_pass, db_host, db_name ]

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
