pipeline:
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/fec-sheet

  helm_deploy:
    image: peloton/drone-helm
    chart: ./charts/sheet
    release: sheets
    values: db.user=${DB_USER},db.pass=${DB_PASS},db.host=${DB_HOST},db.name=${DB_NAME},image.repository=publicintegrity/fec-sheet
    prefix: 
    namespace: sheets
    secrets: [ api_server, kubernetes_token, db_user, db_pass, db_host, db_name ]
    skip_tls_verify: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
