[environments]
  [environments.development]
    name = "sheet"
    namespace = "sheet"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
    set = ["db.user=","db.pass=","db.host=","db.name="]